### ISSUE TITLE
Feedback eerste versie mobile first

### ISSUE THREAD

**Issue by Shannafdnd** [latoyaln/the-startup-responsive-interactieve-website#1]
Tops:
- Goed gebruikt van custom properties
- Je hebt al media ookal hoefde dat nog niet
- Javascript gebruikt! Werkt goed
- Code en website zien er netjes uit 

Tips:
- Comments bij je code zetten
- De afbeelding in de banner is raar gekropt. Dit kan je oplossen door:     background-position: center;
- Probeer dezelfde margins en line-height als de triple website aan te houden.

**Comment by latoyaln** [comment]
Ik heb de issue opgelost door comments toe te voegen, de afbeelding anders te croppen en dezelfde margins te gebruiken 4811587
