### ISSUE TITLE
Hamburger menu is een div, kan beter een button

### ISSUE THREAD

**Issue by Robin1224** [latoyaln/the-startup-responsive-interactieve-website#10]
https://github.com/latoyaln/the-startup-responsive-interactieve-website/blob/c459978244b07918f2bb451e247a073c5f74799a/index.html#L35-L39

Het hamburger menu is een div element. Het zou volgens mij semantisch beter zijn als dit een button element was, omdat het een interactie geeft op de pagina.

Misschien zou het beter zijn om van dit element een button te maken in plaats van een div, omdat dit semantisch (voor screenreaders ook) aangeeft dat het een interactief element is.

**Comment by latoyaln** [comment]
Ik heb de issue opgelost door de div te veranderen in een button [7ea64a5](https://github.com/latoyaln/the-startup-responsive-interactieve-website/commit/7ea64a553fa41df8b6f0765aa32485dadb42784e)
