### ISSUE TITLE
Buttons kleur wijziging

### ISSUE THREAD

**Issue by aliceafanasieva** [latoyaln/the-startup-responsive-interactieve-website#11]
Er moet nog de kleur van de button worden gewijzigd, het is nu zwart als die inactief is, maar ik denk dat het beter zal zijn, als de active state van de button just zwart is, en inactieve - wit. 

https://github.com/latoyaln/the-startup-responsive-interactieve-website/blob/6162d20c41c8e735b0d029dc9e340281ff051967/styles/TeamIOS-style.css#L296-L312

Misschien helpt het om de voorbeelden van buttons te bekijken op deze website, het gaat hier over customizing van de buttons:
[https://getcssscan.com/css-buttons-examples](url)

**Comment by latoyaln** [comment]
Dit is opgelost doordat ik andere iconen gebruik voor de buttons [a32341b](https://github.com/latoyaln/the-startup-responsive-interactieve-website/commit/a32341be2f180d63f92766db1a405e413c7d7ce0)
