### ISSUE TITLE
Gebruik een fallback font voor @fontface

### ISSUE THREAD

**Issue by Tindyy** [latoyaln/the-startup-responsive-interactieve-website#2]
```css
@font-face {
    font-family: 'Rubik';
``` 

https://css-tricks.com/books/greatest-css-tricks/perfect-font-fallbacks/

**Comment by latoyaln** [comment]
Solved by adding fallback fonts [c7feca1](https://github.com/latoyaln/the-startup-responsive-interactieve-website/commit/c7feca15a70150c959a30447da2ea73628b75479)
