### ISSUE TITLE
Gebruik een alt bij img element

### ISSUE THREAD

**Issue by Tindyy** [latoyaln/the-startup-responsive-interactieve-website#3]
```html
<img src="assets/images/Triple_Logo_White.png">↩
``` 

gebruik alt bij een img element voor wanneer de img niet kan laden of voor screenreaders.

https://www.w3schools.com/tags/att_img_alt.asp

**Comment by latoyaln** [comment]
fixed issue door een alt toe te voegen [d67f0cc](https://github.com/latoyaln/the-startup-responsive-interactieve-website/commit/d67f0cc06753ca722064c4581e9d6d2d50afe244)
