### ISSUE TITLE
Een link kan niet in een button

### ISSUE THREAD

**Issue by zoepje** [latoyaln/the-startup-responsive-interactieve-website#4]
https://github.com/latoyaln/the-startup-responsive-interactieve-website/blob/8386e5931c2ae8041f806ccc027f91b0433921d5/index.html#L93

Je hebt een `a` in een `button` kun je dit niet gewoon een `a` maken?

Lees meer over `a` en `button` hier:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button

**Comment by latoyaln** [comment]
Deze issue heb ik gesolved doordat ik de button tag heb verwijderd en de a heb ik een class gegeven zodat ik alsnog de style kan toepassen hierop [a8c24d4](https://github.com/latoyaln/the-startup-responsive-interactieve-website/commit/a8c24d4468ff02938907ab4f5840da6fbef8bdcc)
 ·
