### ISSUE TITLE
Je hebt meerdere H1 elementen

### ISSUE THREAD

**Issue by zoepje** [latoyaln/the-startup-responsive-interactieve-website#5]
https://github.com/latoyaln/the-startup-responsive-interactieve-website/blob/8386e5931c2ae8041f806ccc027f91b0433921d5/index.html#L90-L91

Je maakt gebruik van een H1 in je footer. Een H1 staat normaal boven aan de website en niet in de footer. Ook gebruik je meer dan 1 H1 en dat is niet helemaal netjes. Kun je hier misschien een h2/3 voor gebruiken?

Hier kun je meer over headings elementen lezen:

- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements

- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements#avoid_using_multiple_h1_elements_on_one_page

**Comment by latoyaln** [comment]
Ik heb de issue opgelost door de H1 aan te passen naar een H2.Ook heb ik de teksten samen gevoegd naar 1 lijn [0795c5a](https://github.com/latoyaln/the-startup-responsive-interactieve-website/commit/0795c5a71a740504281164d77a453c9909e7687e)
